[versions]
spring-boot = "4.0.3"
spring-dependency-management = "1.1.7"
ben-manes-versions = "0.53.0"
cyclonedx-bom = "3.2.0"
gradle-git-properties = "2.5.7"
avast-docker-compose = "0.17.21"
hmcts-crime-template = "2.0.2"
jjwt = "0.13.0"
swagger-core = "2.2.43"
junit-bom = "6.0.3"
logstash-logback-encoder = "9.0"
owasp-encoder = "1.4.0"
lombok = "1.18.42"
mapstruct = "1.6.3"
testcontainers = "1.21.4"

[libraries]
hmcts-crime-template = { module = "uk.gov.hmcts.cp:api-hmcts-crime-template", version.ref = "hmcts-crime-template" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
hibernate-validator = { module = "org.hibernate.validator:hibernate-validator" }
spring-boot-starter-opentelemetry = { module = "org.springframework.boot:spring-boot-starter-opentelemetry" }
jjwt = { module = "io.jsonwebtoken:jjwt", version.ref = "jjwt" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
swagger-core = { module = "io.swagger.core.v3:swagger-core", version.ref = "swagger-core" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash-logback-encoder" }
log4j-to-slf4j = { module = "org.apache.logging.log4j:log4j-to-slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic" }
logback-core = { module = "ch.qos.logback:logback-core" }
owasp-encoder = { module = "org.owasp.encoder:encoder", version.ref = "owasp-encoder" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-aspectj = { module = "org.springframework.boot:spring-boot-starter-aspectj" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
postgresql = { module = "org.postgresql:postgresql" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
flyway-core = { module = "org.flywaydb:flyway-core" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "spring-boot" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions" }
cyclonedx-bom = { id = "org.cyclonedx.bom", version.ref = "cyclonedx-bom" }
gradle-git-properties = { id = "com.gorylenko.gradle-git-properties", version.ref = "gradle-git-properties" }
avast-docker-compose = { id = "com.avast.gradle.docker-compose", version.ref = "avast-docker-compose" }
